{
	"label": "fr Label",
	"alias": "fr Alias",
	"hideFieldsetControls": "fr Hide Fieldset Controls?",
	"hideFieldsetControlsDescription": "fr Hides the fieldset add/remove/sort controls.",
	"toggleAdvanced": "fr Toggle Advanced Options",
	"toggleAdvancedDescription": "fr Show advanced options.",
	"hidePropertyLabels": "fr Hide Property Labels?",
	"hidePropertyLabelsDescription": "fr Hides the property labels.",
	"maxFieldsets": "fr Max Fieldsets",
	"maxFieldsetsDescription": "fr How many Fieldsets are allowed? Entering '1' will disable the controls. Default is unlimited.",
	"enableMultipleFieldsets": "fr Enable Multiple Fieldsets?",
	"enableMultipleFieldsetsDescription": "fr Allows multiple types of fieldsets within this archetype.",
	"hideFieldsetToolbar": "fr Hide Fieldset Toolbar?",
	"hideFieldsetToolbarDescription": "fr Hides the fieldset toolbar that appears when more than one fieldset model appears.",
	"customWrapperClass": "fr Custom Wrapper Class",
	"customWrapperClassDescription": "fr (Optional) Enter a custom CSS class that will be applied to the wrapper div.",
	"cssFile": "fr CSS File",
	"cssFileDescription": "fr Optional) Enter a path for a custom CSS file to be included on the page.",
	"jsFile": "fr JS File",
	"jsFileDescription": "fr (Optional) Enter a path for a custom JS file to be included on the page.",
	"toggleDeveloperMode": "fr Toggle Developer Mode",
	"toggleDeveloperModeDescription": "fr Turn on for developer options.",
	"configModel": "fr Config Model",
	"configModelDescription": "fr Be careful editing the text below, it controls the schema for this archetype.",
	"helpText": "fr Help Text",
	"defaultValue": "fr Default Value",
	"dataType": "fr DataType",
	"required": "fr Required",
	"properties": "fr Properties",
	"labelTemplate": "fr Label Template",
	"select": "fr Select",
	"icon": "fr Icon"
}
