{
	"label": "Label",
	"alias": "Alias", 
	"addFieldset": "Add an item",
	"hideFieldsetControls": "Hide Fieldset Controls?",
	"hideFieldsetControlsDescription": "Hides the fieldset add/remove/sort controls.",
	"toggleAdvanced": "Toggle Advanced Options",
	"toggleAdvancedDescription": "Show advanced options.",
	"hidePropertyLabels": "Hide Property Labels?",
	"hidePropertyLabelsDescription": "Hides the property labels.",
	"maxFieldsets": "Max Fieldsets",
	"maxFieldsetsDescription": "How many Fieldsets are allowed? Entering '1' will disable the controls. Default is unlimited.",
	"enableMultipleFieldsets": "Enable Multiple Fieldsets?",
	"enableMultipleFieldsetsDescription": "Allows multiple types of fieldsets within this archetype.",
	"hideFieldsetToolbar": "Hide Fieldset Toolbar?",
	"hideFieldsetToolbarDescription": "Hides the fieldset toolbar that appears when more than one fieldset model appears.",
	"customWrapperClass": "Custom Wrapper Class",
	"customWrapperClassDescription": "(Optional) Enter a custom CSS class that will be applied to the wrapper div.",
	"cssFile": "CSS File",
	"cssFileDescription": "(Optional) Enter a path for a custom CSS file to be included on the page.",
	"jsFile": "JS File",
	"jsFileDescription": "(Optional) Enter a path for a custom JS file to be included on the page.",
	"toggleDeveloperMode": "Toggle Developer Mode",
	"toggleDeveloperModeDescription": "Turn on for developer options.",
	"configModel": "Config Model",
	"configModelDescription": "Be careful editing the text below, it controls the schema for this archetype.",
	"helpText": "Help Text",
	"defaultValue": "Default Value",
	"dataType": "DataType",
	"required": "Required",
	"regEx": "RegEx Validation",
	"properties": "Properties",
	"labelTemplate": "Label Template",
	"select": "Select",
	"icon": "Icon",
	"enableDisabling": "Enable Fieldset Disabling?",
	"enableDisablingDescription": "Allows fieldsets to be individually enabled/disabled.",
	"deepDatatypeRequest":"Enable Deep Datatype Requests?",
	"deepDatatypeRequestDescription":"Allows for easier datatype interception at the cost of caching performance.",
    "overrideDefaultConverterDescription":"Check this if you wish to use your own custom property value converter.",
    "overrideDefaultConverter":"Override Default Property Value Converter?",
    "enableCloning":"Enable Cloning?",
 	"enableCloningDescription":"Enable Fieldset Cloning.",
	"enableCrossDragging":"Enable Cross-Archetype Dragging?",
	"enableCrossDraggingDescription":"Allows fieldsets to be dragged into other Archetypes.",
  "fieldsetGroups":"Fieldset groups",
  "fieldsetGroupsDescription":"If you have a lot of fieldsets to choose from, you may want to consider grouping them in the fieldset picker. Once you have created your groups here, a group picker will be displayed in the fieldset editor and you can assign your fieldsets to their respective groups.",
  "fieldsetGroupName":"Name",
  "addFieldsetGroup":"Add group"
}
